<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.1 /Users/bernhard.muehl/Downloads/guitar/scene.gltf --transform --types
Author: Ya (https://sketchfab.com/Yarik16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guitar-f8ccd75e8c2648ffbbc9e6208ed919c1
Title: Guitar
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { MeshStandardMaterial } from 'three';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';

	let {
		ref = $bindable(),
		fallback,
		error,
		children,
		onloaded,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref?: THREE.Group }]>;
		fallback?: Snippet;
		onloaded?: () => void;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Object_4: THREE.Mesh;
			Object_5: THREE.Mesh;
			Object_6: THREE.Mesh;
			Object_7: THREE.Mesh;
			Object_9: THREE.Mesh;
			Object_11: THREE.Mesh;
			Object_12: THREE.Mesh;
			Object_14: THREE.Mesh;
			Object_16: THREE.Mesh;
			Object_18: THREE.Mesh;
			Object_20: THREE.Mesh;
			Object_22: THREE.Mesh;
			Object_24: THREE.Mesh;
		};
		materials: {
			body2: THREE.MeshStandardMaterial;
			body1: THREE.MeshStandardMaterial;
			body_facets_guitar: THREE.MeshStandardMaterial;
			body3: THREE.MeshStandardMaterial;
			bridge: THREE.MeshStandardMaterial;
			['neck-head']: THREE.MeshStandardMaterial;
			neck2: THREE.MeshStandardMaterial;
			['bridge-pins-saddle-nut']: THREE.MeshStandardMaterial;
			frets: THREE.MeshStandardMaterial;
			['string5-6']: THREE.MeshStandardMaterial;
			['string1-2-3-4']: THREE.MeshStandardMaterial;
			pattern: THREE.MeshStandardMaterial;
			tuning: THREE.MeshStandardMaterial;
		};
	};

	const material = new MeshStandardMaterial({ color: 0xa6e2a1, wireframe: true });

	const gltf = useGltf<GLTFResult>('/assets/models/guitar/scene.glb', { useDraco: true });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		{onloaded?.()}
		<T.Group position={[0, 0, 0.82]} scale={0.13}>
			<T.Mesh geometry={gltf.nodes.Object_4.geometry} {material} />
			<T.Mesh geometry={gltf.nodes.Object_5.geometry} {material} />
			<T.Mesh
				geometry={gltf.nodes.Object_6.geometry}
				material={gltf.materials.body_facets_guitar}
			/>
			<T.Mesh geometry={gltf.nodes.Object_7.geometry} {material} />
		</T.Group>
		<T.Group rotation={[Math.PI / 2, 0, 0]} scale={[0.15, 0.12, 0.12]}>
			<T.Mesh geometry={gltf.nodes.Object_11.geometry} {material} />
			<T.Mesh geometry={gltf.nodes.Object_12.geometry} {material} />
		</T.Group>
		<T.Mesh
			geometry={gltf.nodes.Object_9.geometry}
			{material}
			position={[0, 0.02, 1.61]}
			scale={[0.11, 0.02, 0.11]}
		/>
		<!-- <T.Mesh -->
		<!-- 	geometry={gltf.nodes.Object_14.geometry} -->
		<!-- 	{material} -->
		<!-- 	position={[0, 0.02, -1.67]} -->
		<!-- 	scale={0.02} -->
		<!-- /> -->
		<T.Mesh
			geometry={gltf.nodes.Object_16.geometry}
			{material}
			position={[0, 0.03, -1.47]}
			scale={[0.11, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_18.geometry}
			{material}
			position={[-0.15, 0.08, 1.52]}
			rotation={[0.51, Math.PI / 2, 0]}
			scale={0.05}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_20.geometry}
			{material}
			position={[-0.03, 0.08, 1.52]}
			rotation={[0.51, Math.PI / 2, 0]}
			scale={0.05}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_22.geometry}
			{material}
			position={[0, 0, 0.82]}
			rotation={[0, 0.69, 0]}
			scale={0.3}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_24.geometry}
			{material}
			position={[0, -0.18, -2.07]}
			rotation={[-0.26, 0, -3.12]}
			scale={[0.04, 0.02, 0.04]}
		/>
	{:catch e}
		{@render error?.(e)}
	{/await}

	{@render children?.({ ref })}
</T.Group>
