<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.1 static/assets/models/guitar/scene.gltf --transfrom --types
Author: Pixel (https://sketchfab.com/stefan.lengyel1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-guitar-757b3b5aaf6d4052933edc329c4f5aa5
Title: Low Poly Guitar.
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { MeshStandardMaterial } from 'three';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';

	let {
		ref = $bindable(),
		fallback,
		error,
		children,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref?: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			['Line001_Material_#295_0']: THREE.Mesh;
		};
		materials: object;
	};

	const gltf = useGltf<GLTFResult>('/assets/models/guitar/scene.glb', { useDraco: true });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation={[-1.56, 1.12, -2.42]}>
			<T.Mesh
				geometry={gltf.nodes['Line001_Material_#295_0'].geometry}
				material={new MeshStandardMaterial({ color: 0xa6e3a1, wireframe: true })}
				position={[0.55, 4.23, -14.53]}
			/>
		</T.Group>
	{:catch e}
		{@render error?.(e)}
	{/await}

	{@render children?.({ ref })}
</T.Group>
