<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.1 static/assets/models/keyboard/scene.gltf --transfrom --types
Author: ElOsitoAzul (https://sketchfab.com/ElOsitoAzul)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mini-keyboard-minimalist-7f2378a74e374412876b1a324b03ed0e
Title: Mini Keyboard minimalist
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { MeshStandardMaterial } from 'three';
	import { T, type Props } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';

	let {
		ref = $bindable(),
		fallback,
		error,
		children,
		onloaded,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref?: THREE.Group }]>;
		fallback?: Snippet;
		onloaded?: () => void;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Object_4: THREE.Mesh;
			Object_6: THREE.Mesh;
			Object_8: THREE.Mesh;
			Object_10: THREE.Mesh;
			Object_12: THREE.Mesh;
			Object_14: THREE.Mesh;
			Object_16: THREE.Mesh;
			Object_18: THREE.Mesh;
			Object_20: THREE.Mesh;
			Object_22: THREE.Mesh;
			Object_24: THREE.Mesh;
			Object_26: THREE.Mesh;
			Object_28: THREE.Mesh;
			Object_30: THREE.Mesh;
			Object_32: THREE.Mesh;
			Object_34: THREE.Mesh;
			Object_36: THREE.Mesh;
			Object_38: THREE.Mesh;
			Object_40: THREE.Mesh;
		};
		materials: {
			Material: THREE.MeshStandardMaterial;
			['Material.004']: THREE.MeshStandardMaterial;
			['Material.002']: THREE.MeshStandardMaterial;
			['Material.003']: THREE.MeshStandardMaterial;
			['Material.001']: THREE.MeshStandardMaterial;
		};
	};

	const material = new MeshStandardMaterial({ color: 0x74c7ec, wireframe: true });

	const dracoLoader = useDraco();
	const gltf = useGltf<GLTFResult>('/assets/models/keyboard/scene.glb', { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		{onloaded?.()}
		<T.Mesh
			geometry={gltf.nodes.Object_4.geometry}
			{material}
			position={[0.13, 0.12, -0.07]}
			scale={[1.5, 0.09, 0.94]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_6.geometry}
			{material}
			position={[-0.04, 0.06, 0.02]}
			scale={[0.24, 0.1, 0.24]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_8.geometry}
			{material}
			position={[-0.92, 0.47, 0.38]}
			scale={[0.15, 0.1, 0.15]}
			interactive
			onclick={() => console.log('clicked')}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_10.geometry}
			{material}
			position={[1.12, 0.38, -0.63]}
			scale={[0.15, 0.1, 0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_12.geometry}
			{material}
			position={[1.15, 0.38, -0.64]}
			scale={[0.21, 0.15, 0.21]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_14.geometry}
			{material}
			position={[-0.42, 0.41, -0.62]}
			scale={[0.15, 0.1, 0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_16.geometry}
			{material}
			position={[0.08, 0.4, -0.62]}
			scale={[0.15, 0.1, 0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_18.geometry}
			{material}
			position={[0.57, 0.39, -0.62]}
			scale={[0.15, 0.1, 0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_20.geometry}
			{material}
			position={[-0.26, 0.4, -0.13]}
			scale={[0.15, 0.1, 0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_22.geometry}
			{material}
			position={[0.24, 0.4, -0.12]}
			scale={[0.15, 0.1, 0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_24.geometry}
			{material}
			position={[0.26, 0.4, 0.38]}
			rotation={[-Math.PI, 0.78, 0]}
			scale={[-0.07, 0.05, 0.07]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_26.geometry}
			{material}
			position={[0.73, 0.49, -0.09]}
			rotation={[0, 0.79, -Math.PI]}
			scale={[-0.07, 0.07, 0.07]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_28.geometry}
			{material}
			position={[0.73, 0.4, 0.36]}
			rotation={[Math.PI, -0.79, 0]}
			scale={[-0.07, 0.05, 0.07]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_30.geometry}
			{material}
			position={[1.2, 0.4, 0.38]}
			rotation={[0, -0.78, -Math.PI]}
			scale={[-0.07, 0.05, 0.07]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_32.geometry}
			{material}
			position={[-0.92, 0.29, -0.61]}
			scale={[0.24, 0.1, 0.24]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_34.geometry}
			{material}
			position={[-0.59, 0.29, 0.39]}
			scale={[0.58, 0.1, 0.24]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_36.geometry}
			{material}
			position={[-0.93, 0.42, -0.6]}
			scale={[0.15, 0.11, 0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_38.geometry}
			{material}
			position={[-0.94, 0.41, -0.12]}
			scale={[0.12, 0.08, 0.12]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_40.geometry}
			{material}
			position={[0.73, 0.29, 0.26]}
			scale={[0.24, 0.1, 0.24]}
		/>
	{:catch e}
		{@render error?.(e)}
	{/await}

	{@render children?.({ ref })}
</T.Group>
