<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.1 static/assets/models/racket/scene.glb --types
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tennis-racket-c314dcce06ba488ca624957f579b8196
Title: Tennis Racket
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { MeshStandardMaterial } from 'three';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';

	let {
		ref = $bindable(),
		fallback,
		error,
		children,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref?: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			['Tennis_Racket_03_-_Default_0']: THREE.Mesh;
			['Tennis_Racket_02_-_Default_0']: THREE.Mesh;
			['Tennis_Racket_07_-_Default_0']: THREE.Mesh;
		};
		materials: {
			['03_-_Default']: THREE.MeshStandardMaterial;
			['02_-_Default']: THREE.MeshStandardMaterial;
			['07_-_Default']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/assets/models/racket/scene.glb', { useDraco: true });

	const material = new MeshStandardMaterial({ color: 0xfab387, wireframe: true });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={[1, 1.38, 0.65]} position={[0, 150, 0]}>
			<T.Mesh geometry={gltf.nodes['Tennis_Racket_03_-_Default_0'].geometry} {material} />
			<T.Mesh geometry={gltf.nodes['Tennis_Racket_02_-_Default_0'].geometry} {material} />
			<T.Mesh geometry={gltf.nodes['Tennis_Racket_07_-_Default_0'].geometry} {material} />
		</T.Group>
	{:catch e}
		{@render error?.(e)}
	{/await}

	{@render children?.({ ref })}
</T.Group>
